# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...

#repo: github.com/willie-lin/cloud-terminal
#binary_name: release
#brew:
#  repo:
#env_files:
#  github_token: d69d712ad344726c05c39b66c728962620d06c87
##  github_token: ~/.path/to/my/gh_token
#  gitlab_token: ~/.path/to/my/gl_token
#  gitea_token: ~/.path/to/my/gitea_token
project_name: SWTAC

builds:
#  -
#    # ID of the build.
#    # Defaults to the project name.
#    id: "my-build"
#
#    # Path to project's (sub)directory containing Go code.
#    # This is the working directory for the Go build command(s).
#    # Default is
#    dir: go
#
#
#    # Path to main.go file or main package.
#    # Default is `.`.
#    main: ./cmd/main.go
#  -
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
