services:
  mysql:
    build:
      context: docker/mysql
      dockerfile: Dockerfile
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=ent
    healthcheck:
      test: ["CMD", "mysql", "-h" , "127.0.0.1" , "-uroot"]
      interval: 5s
      timeout: 5s
      retries: 100
      start_period: 20s
    ports:
      - "3306:3306"