// Code generated by ent, DO NOT EDIT.

package ent

import (
	"SWTAC/datasource/ent/predicate"
	"SWTAC/datasource/ent/usergroup"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserGroupUpdate is the builder for updating UserGroup entities.
type UserGroupUpdate struct {
	config
	hooks    []Hook
	mutation *UserGroupMutation
}

// Where appends a list predicates to the UserGroupUpdate builder.
func (ugu *UserGroupUpdate) Where(ps ...predicate.UserGroup) *UserGroupUpdate {
	ugu.mutation.Where(ps...)
	return ugu
}

// SetUpdatedAt sets the "updated_at" field.
func (ugu *UserGroupUpdate) SetUpdatedAt(t time.Time) *UserGroupUpdate {
	ugu.mutation.SetUpdatedAt(t)
	return ugu
}

// SetCreator sets the "creator" field.
func (ugu *UserGroupUpdate) SetCreator(s string) *UserGroupUpdate {
	ugu.mutation.SetCreator(s)
	return ugu
}

// SetNillableCreator sets the "creator" field if the given value is not nil.
func (ugu *UserGroupUpdate) SetNillableCreator(s *string) *UserGroupUpdate {
	if s != nil {
		ugu.SetCreator(*s)
	}
	return ugu
}

// ClearCreator clears the value of the "creator" field.
func (ugu *UserGroupUpdate) ClearCreator() *UserGroupUpdate {
	ugu.mutation.ClearCreator()
	return ugu
}

// SetEditor sets the "editor" field.
func (ugu *UserGroupUpdate) SetEditor(s string) *UserGroupUpdate {
	ugu.mutation.SetEditor(s)
	return ugu
}

// SetNillableEditor sets the "editor" field if the given value is not nil.
func (ugu *UserGroupUpdate) SetNillableEditor(s *string) *UserGroupUpdate {
	if s != nil {
		ugu.SetEditor(*s)
	}
	return ugu
}

// ClearEditor clears the value of the "editor" field.
func (ugu *UserGroupUpdate) ClearEditor() *UserGroupUpdate {
	ugu.mutation.ClearEditor()
	return ugu
}

// SetDeleted sets the "deleted" field.
func (ugu *UserGroupUpdate) SetDeleted(f float64) *UserGroupUpdate {
	ugu.mutation.ResetDeleted()
	ugu.mutation.SetDeleted(f)
	return ugu
}

// AddDeleted adds f to the "deleted" field.
func (ugu *UserGroupUpdate) AddDeleted(f float64) *UserGroupUpdate {
	ugu.mutation.AddDeleted(f)
	return ugu
}

// SetParentID sets the "parent_id" field.
func (ugu *UserGroupUpdate) SetParentID(s string) *UserGroupUpdate {
	ugu.mutation.SetParentID(s)
	return ugu
}

// SetName sets the "name" field.
func (ugu *UserGroupUpdate) SetName(s string) *UserGroupUpdate {
	ugu.mutation.SetName(s)
	return ugu
}

// SetCode sets the "code" field.
func (ugu *UserGroupUpdate) SetCode(s string) *UserGroupUpdate {
	ugu.mutation.SetCode(s)
	return ugu
}

// SetIntro sets the "intro" field.
func (ugu *UserGroupUpdate) SetIntro(s string) *UserGroupUpdate {
	ugu.mutation.SetIntro(s)
	return ugu
}

// Mutation returns the UserGroupMutation object of the builder.
func (ugu *UserGroupUpdate) Mutation() *UserGroupMutation {
	return ugu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ugu *UserGroupUpdate) Save(ctx context.Context) (int, error) {
	ugu.defaults()
	return withHooks(ctx, ugu.sqlSave, ugu.mutation, ugu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ugu *UserGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := ugu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ugu *UserGroupUpdate) Exec(ctx context.Context) error {
	_, err := ugu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ugu *UserGroupUpdate) ExecX(ctx context.Context) {
	if err := ugu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ugu *UserGroupUpdate) defaults() {
	if _, ok := ugu.mutation.UpdatedAt(); !ok {
		v := usergroup.UpdateDefaultUpdatedAt()
		ugu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ugu *UserGroupUpdate) check() error {
	if v, ok := ugu.mutation.Creator(); ok {
		if err := usergroup.CreatorValidator(v); err != nil {
			return &ValidationError{Name: "creator", err: fmt.Errorf(`ent: validator failed for field "UserGroup.creator": %w`, err)}
		}
	}
	return nil
}

func (ugu *UserGroupUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ugu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(usergroup.Table, usergroup.Columns, sqlgraph.NewFieldSpec(usergroup.FieldID, field.TypeUUID))
	if ps := ugu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ugu.mutation.UpdatedAt(); ok {
		_spec.SetField(usergroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ugu.mutation.Creator(); ok {
		_spec.SetField(usergroup.FieldCreator, field.TypeString, value)
	}
	if ugu.mutation.CreatorCleared() {
		_spec.ClearField(usergroup.FieldCreator, field.TypeString)
	}
	if value, ok := ugu.mutation.Editor(); ok {
		_spec.SetField(usergroup.FieldEditor, field.TypeString, value)
	}
	if ugu.mutation.EditorCleared() {
		_spec.ClearField(usergroup.FieldEditor, field.TypeString)
	}
	if value, ok := ugu.mutation.Deleted(); ok {
		_spec.SetField(usergroup.FieldDeleted, field.TypeFloat64, value)
	}
	if value, ok := ugu.mutation.AddedDeleted(); ok {
		_spec.AddField(usergroup.FieldDeleted, field.TypeFloat64, value)
	}
	if value, ok := ugu.mutation.ParentID(); ok {
		_spec.SetField(usergroup.FieldParentID, field.TypeString, value)
	}
	if value, ok := ugu.mutation.Name(); ok {
		_spec.SetField(usergroup.FieldName, field.TypeString, value)
	}
	if value, ok := ugu.mutation.Code(); ok {
		_spec.SetField(usergroup.FieldCode, field.TypeString, value)
	}
	if value, ok := ugu.mutation.Intro(); ok {
		_spec.SetField(usergroup.FieldIntro, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ugu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usergroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ugu.mutation.done = true
	return n, nil
}

// UserGroupUpdateOne is the builder for updating a single UserGroup entity.
type UserGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserGroupMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (uguo *UserGroupUpdateOne) SetUpdatedAt(t time.Time) *UserGroupUpdateOne {
	uguo.mutation.SetUpdatedAt(t)
	return uguo
}

// SetCreator sets the "creator" field.
func (uguo *UserGroupUpdateOne) SetCreator(s string) *UserGroupUpdateOne {
	uguo.mutation.SetCreator(s)
	return uguo
}

// SetNillableCreator sets the "creator" field if the given value is not nil.
func (uguo *UserGroupUpdateOne) SetNillableCreator(s *string) *UserGroupUpdateOne {
	if s != nil {
		uguo.SetCreator(*s)
	}
	return uguo
}

// ClearCreator clears the value of the "creator" field.
func (uguo *UserGroupUpdateOne) ClearCreator() *UserGroupUpdateOne {
	uguo.mutation.ClearCreator()
	return uguo
}

// SetEditor sets the "editor" field.
func (uguo *UserGroupUpdateOne) SetEditor(s string) *UserGroupUpdateOne {
	uguo.mutation.SetEditor(s)
	return uguo
}

// SetNillableEditor sets the "editor" field if the given value is not nil.
func (uguo *UserGroupUpdateOne) SetNillableEditor(s *string) *UserGroupUpdateOne {
	if s != nil {
		uguo.SetEditor(*s)
	}
	return uguo
}

// ClearEditor clears the value of the "editor" field.
func (uguo *UserGroupUpdateOne) ClearEditor() *UserGroupUpdateOne {
	uguo.mutation.ClearEditor()
	return uguo
}

// SetDeleted sets the "deleted" field.
func (uguo *UserGroupUpdateOne) SetDeleted(f float64) *UserGroupUpdateOne {
	uguo.mutation.ResetDeleted()
	uguo.mutation.SetDeleted(f)
	return uguo
}

// AddDeleted adds f to the "deleted" field.
func (uguo *UserGroupUpdateOne) AddDeleted(f float64) *UserGroupUpdateOne {
	uguo.mutation.AddDeleted(f)
	return uguo
}

// SetParentID sets the "parent_id" field.
func (uguo *UserGroupUpdateOne) SetParentID(s string) *UserGroupUpdateOne {
	uguo.mutation.SetParentID(s)
	return uguo
}

// SetName sets the "name" field.
func (uguo *UserGroupUpdateOne) SetName(s string) *UserGroupUpdateOne {
	uguo.mutation.SetName(s)
	return uguo
}

// SetCode sets the "code" field.
func (uguo *UserGroupUpdateOne) SetCode(s string) *UserGroupUpdateOne {
	uguo.mutation.SetCode(s)
	return uguo
}

// SetIntro sets the "intro" field.
func (uguo *UserGroupUpdateOne) SetIntro(s string) *UserGroupUpdateOne {
	uguo.mutation.SetIntro(s)
	return uguo
}

// Mutation returns the UserGroupMutation object of the builder.
func (uguo *UserGroupUpdateOne) Mutation() *UserGroupMutation {
	return uguo.mutation
}

// Where appends a list predicates to the UserGroupUpdate builder.
func (uguo *UserGroupUpdateOne) Where(ps ...predicate.UserGroup) *UserGroupUpdateOne {
	uguo.mutation.Where(ps...)
	return uguo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uguo *UserGroupUpdateOne) Select(field string, fields ...string) *UserGroupUpdateOne {
	uguo.fields = append([]string{field}, fields...)
	return uguo
}

// Save executes the query and returns the updated UserGroup entity.
func (uguo *UserGroupUpdateOne) Save(ctx context.Context) (*UserGroup, error) {
	uguo.defaults()
	return withHooks(ctx, uguo.sqlSave, uguo.mutation, uguo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uguo *UserGroupUpdateOne) SaveX(ctx context.Context) *UserGroup {
	node, err := uguo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uguo *UserGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := uguo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uguo *UserGroupUpdateOne) ExecX(ctx context.Context) {
	if err := uguo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uguo *UserGroupUpdateOne) defaults() {
	if _, ok := uguo.mutation.UpdatedAt(); !ok {
		v := usergroup.UpdateDefaultUpdatedAt()
		uguo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uguo *UserGroupUpdateOne) check() error {
	if v, ok := uguo.mutation.Creator(); ok {
		if err := usergroup.CreatorValidator(v); err != nil {
			return &ValidationError{Name: "creator", err: fmt.Errorf(`ent: validator failed for field "UserGroup.creator": %w`, err)}
		}
	}
	return nil
}

func (uguo *UserGroupUpdateOne) sqlSave(ctx context.Context) (_node *UserGroup, err error) {
	if err := uguo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usergroup.Table, usergroup.Columns, sqlgraph.NewFieldSpec(usergroup.FieldID, field.TypeUUID))
	id, ok := uguo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserGroup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uguo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usergroup.FieldID)
		for _, f := range fields {
			if !usergroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usergroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uguo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uguo.mutation.UpdatedAt(); ok {
		_spec.SetField(usergroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := uguo.mutation.Creator(); ok {
		_spec.SetField(usergroup.FieldCreator, field.TypeString, value)
	}
	if uguo.mutation.CreatorCleared() {
		_spec.ClearField(usergroup.FieldCreator, field.TypeString)
	}
	if value, ok := uguo.mutation.Editor(); ok {
		_spec.SetField(usergroup.FieldEditor, field.TypeString, value)
	}
	if uguo.mutation.EditorCleared() {
		_spec.ClearField(usergroup.FieldEditor, field.TypeString)
	}
	if value, ok := uguo.mutation.Deleted(); ok {
		_spec.SetField(usergroup.FieldDeleted, field.TypeFloat64, value)
	}
	if value, ok := uguo.mutation.AddedDeleted(); ok {
		_spec.AddField(usergroup.FieldDeleted, field.TypeFloat64, value)
	}
	if value, ok := uguo.mutation.ParentID(); ok {
		_spec.SetField(usergroup.FieldParentID, field.TypeString, value)
	}
	if value, ok := uguo.mutation.Name(); ok {
		_spec.SetField(usergroup.FieldName, field.TypeString, value)
	}
	if value, ok := uguo.mutation.Code(); ok {
		_spec.SetField(usergroup.FieldCode, field.TypeString, value)
	}
	if value, ok := uguo.mutation.Intro(); ok {
		_spec.SetField(usergroup.FieldIntro, field.TypeString, value)
	}
	_node = &UserGroup{config: uguo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uguo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usergroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uguo.mutation.done = true
	return _node, nil
}
